---
- hosts: all
  become: true

  tasks:
  - name: Install Apache
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
      - apache2
      - apache2-utils

  - name: Enable Apache Server Side Include module
    apache2_module: name=include state=present
    notify: restart apache

  - name: Set default Apache site config
    template: src=./default-site.conf dest=/etc/apache2/sites-available/000-default.conf
    notify: restart apache

  - name: Ensure Apache is started and enabled
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
